Name:                   resnet50-1k-classifier-deployment
Namespace:              default
CreationTimestamp:      Fri, 03 Jan 2025 02:16:39 -0600
Labels:                 app=resnet50-1k-classifier
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=resnet50-1k-classifier
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=resnet50-1k-classifier
  Containers:
   resnet50-1k-classifier:
    Image:         resnet-k8s:latest
    Port:          7860/TCP
    Host Port:     0/TCP
    Environment:   <none>
    Mounts:        <none>
  Volumes:         <none>
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   resnet50-1k-classifier-deployment-5cd5cf566c (2/2 replicas created)
Events:
  Type    Reason             Age   From                   Message
  ----    ------             ----  ----                   -------
  Normal  ScalingReplicaSet  36m   deployment-controller  Scaled up replica set resnet50-1k-classifier-deployment-5cd5cf566c to 2
