#kubectl describe deployment.apps/food-classifier-deployment

Name:                   food-classifier-deployment
Namespace:              default
CreationTimestamp:      Sun, 15 Dec 2024 20:04:33 -0600
Labels:                 app=food-classifier
Annotations:            deployment.kubernetes.io/revision: 1
Selector:               app=food-classifier
Replicas:               2 desired | 2 updated | 2 total | 2 available | 0 unavailable
StrategyType:           RollingUpdate
MinReadySeconds:        0
RollingUpdateStrategy:  25% max unavailable, 25% max surge
Pod Template:
  Labels:  app=food-classifier
  Containers:
   food-classifier:
    Image:         food-classifier-k8s:latest
    Port:          7860/TCP
    Host Port:     0/TCP
    Environment:   <none>
    Mounts:        <none>
  Volumes:         <none>
  Node-Selectors:  <none>
  Tolerations:     <none>
Conditions:
  Type           Status  Reason
  ----           ------  ------
  Available      True    MinimumReplicasAvailable
  Progressing    True    NewReplicaSetAvailable
OldReplicaSets:  <none>
NewReplicaSet:   food-classifier-deployment-5c7b447778 (2/2 replicas created)
Events:          <none>